alter table public.connected_devices add column if not exists acquisition_mode text;
update public.connected_devices set acquisition_mode=case when source_type='mobile' then 'smartphone' else 'external_logger' end where acquisition_mode is null;
alter table public.connected_devices alter column acquisition_mode set default 'external_logger';
alter table public.connected_devices alter column acquisition_mode set not null;
alter table public.connected_devices drop constraint if exists connected_devices_acquisition_mode_check;
alter table public.connected_devices add constraint connected_devices_acquisition_mode_check check (acquisition_mode = any (array['smartphone'::text,'external_logger'::text,'hybrid'::text]));

create or replace function public.set_connected_device_acquisition_mode(p_team_id uuid,p_device_id uuid,p_mode text) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare d public.connected_devices%rowtype; begin if not public.has_team_permission(p_team_id,'devices.edit') then raise exception 'Permesso devices.edit richiesto'; end if; if p_mode not in ('smartphone','external_logger','hybrid') then raise exception 'Modalità acquisizione non valida'; end if; update public.connected_devices set acquisition_mode=p_mode where id=p_device_id and team_id=p_team_id returning * into d; if not found then raise exception 'Dispositivo non trovato'; end if; return jsonb_build_object('id',d.id,'acquisition_mode',d.acquisition_mode); end; $function$;
revoke all on function public.set_connected_device_acquisition_mode(uuid,uuid,text) from public; grant execute on function public.set_connected_device_acquisition_mode(uuid,uuid,text) to authenticated,service_role;

create or replace function public.get_connected_device_runtime_config(p_device_key text) returns jsonb language plpgsql stable security definer set search_path='public','extensions' as $function$
declare k public.connected_device_keys%rowtype; d public.connected_devices%rowtype; v_hash text; begin if coalesce(char_length(p_device_key),0)<20 then raise exception 'Chiave dispositivo non valida'; end if; v_hash:=encode(digest(p_device_key,'sha256'),'hex'); select * into k from public.connected_device_keys where key_hash=v_hash and revoked_at is null and (expires_at is null or expires_at>now()) order by created_at desc limit 1; if not found then raise exception 'Credenziale dispositivo non valida o revocata'; end if; select * into d from public.connected_devices where id=k.device_id and team_id=k.team_id and status='active'; if not found then raise exception 'Dispositivo non attivo'; end if; return jsonb_build_object('device_id',d.id,'car_id',d.car_id,'name',d.name,'source_type',d.source_type,'acquisition_mode',d.acquisition_mode,'default_driver_id',d.default_driver_id,'capabilities',coalesce(d.capabilities,'{}'::jsonb)); end; $function$;
revoke all on function public.get_connected_device_runtime_config(text) from public; grant execute on function public.get_connected_device_runtime_config(text) to anon,authenticated,service_role;
